### ISSUE TITLE
Singleplayer pause button sometimes disappears

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/custom_hero_clash_issues#669]
![image](https://user-images.githubusercontent.com/63279022/103165243-592fc180-4869-11eb-9e6b-34c160632822.png)

**Comment by HappyFeedFriends** [comment]
sven alive, after it is defeated, the pause is activated.

**Comment by Draze22** [comment]
He has disconnected, just hasn't abandoned yet.

**Comment by HappyFeedFriends** [comment]
Exactly

**Comment by Draze22** [comment]
But he is dead, it doesn't matter if he comes back right?

**Comment by HappyFeedFriends** [comment]
I agree

**Comment by Draze22** [comment]
Is Sven not having abandoned causing this bug?

**Comment by Draze22** [comment]
@HappyFeedFriends does this help?
![image](https://user-images.githubusercontent.com/63279022/103167109-54c0d400-487c-11eb-8ad1-ace1e847dde6.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch

**Comment by Draze22** [comment]
This is still happening.

![image](https://user-images.githubusercontent.com/63279022/112776924-9d12ac80-908c-11eb-8a9d-aaf68e63af29.png)
![image](https://user-images.githubusercontent.com/63279022/112776946-a69c1480-908c-11eb-8abc-1b3efb91b09b.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/112781526-be789600-9096-11eb-8e60-500513500e6a.png)
![image](https://user-images.githubusercontent.com/63279022/112781571-d2bc9300-9096-11eb-9095-a638773d2ce8.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/112782239-490dc500-9098-11eb-86da-ced730fbb46e.png)
